FROM antora/antora

# Install inotify-tools to provide the inotifywait command that detects when
# source files have changed, which in turn can be used to re-run the antora
# command (to rebuild the documentation set).
RUN apk add --no-cache inotify-tools
